### ISSUE TITLE
Cannot find mime.types on FreeBSD (cleanup config task removes all files in specified path)

### ISSUE THREAD

**Issue by vladp** [nginxinc/ansible-role-nginx#136] opened 2019-06-06 06:26 UTC
Hello,
I cannot seem to find mime.types (referred by main nginx.conf.j2) 
when using this role to install on FreeBSD 12.

my role code is:

```
---
# I have to set nginxconfigdir__root to /usr/local/etc/nginx on FreeBSD (on lnx it is /etc/nginx)
# (also will need to modify default template, because it hardcodes the pass to linux default, and does nto work on freebsd
# 
- name: install nginx | restapi
  include_role:
    name: nginxinc.nginx
    apply: 
      become: yes
  vars:
    nginx_type: opensource
    # this role has a problem installing modules for fbsd or obsd.
    # disable for now
#    nginx_modules:
#      image_filter: true
#      geoip: true
        
    # Remove previously existing NGINX configuration files.
    nginx_cleanup_config: true
    nginx_cleanup_config_path:
      - "{{ nginxconfigdir__root }}/config.d"  

    nginx_main_template_enable: true
    nginx_main_template:
      template_file: nginx.conf.j2 
      conf_file_name: nginx.conf
      conf_file_location: "{{ nginxconfigdir__root }}"  # I have to set it to /usr/local/etc/nginx on FreeBSD (on lnx it is /etc/nginx)
      user: nginx
      worker_processes: auto
      error_level: warn
      worker_connections: 1024
      http_enable: true
      http_settings:
        keepalive_timeout: 65
        cache: false
        rate_limit: false
        keyval: false
      stream_enable: true
      http_global_autoindex: false


    nginx_stream_template_enable: true
    nginx_stream_template:
      default:  
        template_file:  stream/default.conf.j2
        conf_file_name: restapi__beX.conf
        conf_file_location: "{{ nginxconfigdir__root }}/conf.d/stream"
        network_streams:
          default:
            listen_address: localhost
            listen_port: 4998
            udp_enable: false
            proxy_pass: mybackend
            proxy_timeout: 3s
            proxy_connect_timeout: 1s
            proxy_protocol: false
            health_check_plus: false
            proxy_ssl: 
              cert: "{{ currdomainCertDir }}/{{ certfile__fullchain }}"
              key: "{{ currdomainCertDir }}/{{ certfile__privkey }}"
              password_file: "{{ currdomainCertDir }}/{{ certfile__pass }}"
              protocols: TLSv1 TLSv1.1 TLSv1.2 TLSv1.3
              ciphers: HIGH:!aNULL:!MD5
              verify: false
              verify_depth: 1
              session_reuse: true  
              
        upstreams:
          upstream1: 
            name: mybackend
            zone_name: mybackend
            lb_method: least_conn
            sticky_cookie: false
            zone_size: 64k
            servers:
              server1:
                address: 10.0.1.99
                port: 77777
                weight: 1
                healthcheck: max_fails=2 fail_timeout=10s
              server2:
                address: 10.0.1.999
                port: 88888
                weight: 1
                healthcheck: max_fails=2 fail_timeout=10s

```

**Comment by alessfg** [comment] 2019-06-06 12:20
Hi @vladp!

As you may have figured already, the issue is that the default location for `mime.types` is set to `/etc/nginx/mime.types`, but in FreeBSD the location is `/usr/local/etc/nginx/mime.types`. There's an open PR that should fix this issue (#87) and a few other FreeBSD path related issues once merged.

For now the easiest solution/workaround is to manually modify the default template to change the paths. Once that PR is merged there'll hopefully be better support for FreeBSD out of the box.

Cheers,
Alessandro.

**Comment by vladp** [comment] 2019-06-06 15:28
Thank you Alessandro.
I re-run my FreeBSD tests again (did not openBSD yet) -- and what seems to be happening is the following

a) all of the supporting files (eg mime.types) get correctly installed into the root of the nginx config
(in freeBSD it is /usr/local/etc/nginx )

b) when directive 
```
nginx_cleanup_config: true 
nginx_cleanup_config_path:
   - /usr/local/etc/nginx 

```
is used, the role deletes correctly all configs
But then, it reinstall only the   /usr/local/etc/nginx.conf, and all the generated files (again correctly) 
at /usr/local/etc/nginx/conf.d

The problem is, it does not reinstall mime.types and all the files that were initially installed by the role when the ports build is finished.

It seems that anything generated from templates is reinstalled correctly.
But anything that came from the build process does not get reinstalled.


This seems to be different from Linux, where on Linux the above directives will still cause the supporting config files to be correctly installed.

--- 
The way I am working around this issue is to never use
```
nginx_cleanup_config_path:
   - /usr/local/etc/nginx 

```
and, instead, use

```
nginx_cleanup_config_path:
   - /usr/local/etc/nginx/conf.d

```

For a bit of background:

My ansible scripts support 'idempotent' behaviour  -- meaning that they are safe to apply to the same hosts multiple times:  they will leave the target in same state (regardless of how often they are applied).

Because of the above behaviour, to keep idempotentcy  for FreeBSD (and OpenBSD) -- I am basically avoiding deleting   the /usr/local/etc/nginx, and only touching /usr/local/etc/nginx/conf.d

not sure if this is the behaviour you would expect or not.
If this works as expected  -- this issue can be closed.

Thank you again for fast and helpful follow-ups.

**Comment by alessfg** [comment] 2019-06-06 21:45
That is the intended behaviour at the moment, with ideally the folder to be removed being the `conf.d` file you mentioned. However, you raise a good point that `nginx.conf` should be removed too. I'll leave this open till I have some time to change this.

**Comment by vladp** [comment] 2019-06-06 22:32
I believe nginx.conf is removed when clean up path is: `/usr/local/etc/nginx `

My challenge (and may be a mis-understanding) was that once `/usr/local/etc/nginx ` in was removed,
when the role applied second time -- the files such as  `fastcgi_params  koi-utf  koi-win  mime.types` where not re-created (and that was FreeBSD specific, I though)
So second time the role was applied on FreeBSD the configs did not work because mime.types was referenced from nginx.conf -- and mime.types was missing completely from the target host (as it was deleted and not re-created).

**Comment by alessfg** [comment] 2019-06-07 11:48
Yeah I understood as much. The cleanup path should not be your main NGINX path. It should be the path where you contain most/all your non `nginx.conf` files (eg `/usr/local/etc/nginx/conf.d`). I'll add some more documentation to the README. Hopefully that helps!

**Closed** 2020-06-12 21:42 UTC
Labels: bug
